#include <cassert>

#include "all_function.h"

int main()
{
    StdExept();
    /*assert(2 + 2 == 4);
    std::cout << "Execution continues past the first assert\n";
    assert(2 + 2 == 5);
    std::cout << "Execution continues past the second assert\n";
    
    Output:
    Execution continues past the first assert
        Assertion failed : 2 + 2 == 5,*/
    return 0;
}